### ISSUE TITLE
google api interaction w/ react DOM

### ISSUE THREAD

**Issue by kjkang11** [simplenclean/looking-for-group#20]

**Comment by rhiroy** [comment]
I am currently going through this tutorial: https://www.fullstackreact.com/articles/how-to-write-a-google-maps-react-component/ to understand the best practice for integrating React w/ Google Maps API, so as to maximize modularization. 

This will also enable me to complete my day's goal of getting Google Map Markers (or Pins, as we are calling them) to function.

I will also let Kenny know as soon as I come across any information that will be relevant to him.
